export enum PokemonLocationMethods {
  walk = 'Walking in tall grass or a cave',
  'old-rod' = 'Fishing with an Old Rod',
  'good-rod' = 'Fishing with a Good Rod',
  'super-rod' = 'Fishing with a Super Rod',
  surf = 'Surfing',
  'rock-smash' = 'Smashing rocks',
  headbutt = 'Headbutting trees',
  'dark-grass' = 'Walking in dark grass',
  'grass-spots' = 'Walking in rustling grass',
  'cave-spots' = 'Walking in dust clouds',
  'bridge-spots' = 'Walking in bridge shadows',
  'super-rod-spots' = 'Fishing in dark spots',
  'surf-spots' = 'Surfing in dark spots',
  'yellow-flowers' = 'Walking in yellow flowers',
  'purple-flowers' = 'Walking in purple flowers',
  'red-flowers' = 'Walking in red flowers',
  'rough-terrain' = 'Walking on rough terrain',
  gift = 'Receive as a gift',
  'gift-egg' = 'Receive egg as a gift',
  'only-one' = 'Static encounter, only one chance',
  pokeflute = 'Playing Pokéflute',
  'headbutt-low' = 'Headbutting a low encounter rate tree',
  'headbutt-normal' = 'Headbutting a normal encounter rate tree',
  'headbutt-high' = 'Headbutting a high encounter rate tree', // headbutt
  'squirt-bottle' = 'Using the Squirt Bottle on a Sudowoodo', // regador
  'wailmer-pail' = 'Using the Wailmer Pail on a Sudowoodo', // regador
  seaweed = 'Diving on seaweed', // alga marinha?
  'roaming-grass' = 'On any overworld patch of grass', // qualquer bloquinho de grama
  'roaming-water' = 'On any overworld water tile', // qualquer bloquinho de agua
  'devon-scope' = 'Using Devon Scope', // usando devon-scope
  'feebas-tile-fishing' = 'Fishing in a Feebas Tile' // bloquinho de agua de feebas
}
